### ISSUE TITLE
Unresolvable dependency resolving [Parameter #3 [ <required> callable $isDownForMaintenance ]] in class Illuminate\Queue\Worker

### ISSUE THREAD

**Issue by arthur798** [dusterio/laravel-aws-worker#66]
I am getting this error when scheduling any type of job, what could be wrong? I am running laravel 6.10

**Comment by mccahan** [comment]
Do you happen to be using the Lumen provider, Dusterio\AwsWorker\Integrations\LumenServiceProvider? I have a pull request in on the same error message when using that one, #67

**Comment by sinemacula** [comment]
I know what is causing this... It is the following line:

https://github.com/dusterio/laravel-aws-worker/blob/68d2d62d3888c70f74d0bb7dda91899fe8eaa158/src/Integrations/LumenServiceProvider.php#L50

`$this->app->version()` returns a `string`, not an `integer`, thus this condition never succeeds. That said, I am confused as to how this seems to be working for others... Can anyone elaborate on this?

**Comment by dusterio** [comment]
@sinemacula I can see that Laravel returns a float, but Lumen returns a string. Is it possible that previous versions of Lumen returned float? This would explain it - maybe the "others" are on older versions?

**Comment by sinemacula** [comment]
@dusterio I checked the Lumen framework code and it seems that the `Application` class has always returned a string. I assume that the only reason this has not been raised sooner is because most people use Laravel, not Lumen, and on top of that, not everyone has upgraded to version 6 so it is only a few people that would have noticed this issue...

Thank you for merging :-D
