### ISSUE TITLE
Not reading the environment variables

### ISSUE THREAD

**Issue by arjunksankar** [dusterio/laravel-aws-worker#74]
Hi
I am using this package for running my crons. But I am facing an issue that it is not reading the environment variables which are set in the elastic beanstalk... But It works fine when I execute the command manually from my terminal..Can you please look into this issue?

**Comment by dusterio** [comment]
@arjunksankar are you using config() helper in the code that in turn uses env() function?

**Comment by arjunksankar** [comment]
@dusterio  Yes, I am using the default config which uses the env function... 

'default' => env('DB_CONNECTION', 'mysql'),

**Comment by fylzero** [comment]
@arjunksankar Sorry this got lost in the shuffle, unfortunately this issue is likely due to a misconfiguration or possibly config caching, idk. This doesn't seem to be related directly to this package so I am marking this closed. If you come across anything specific that points to the package being the problem please open a new issue. Thanks!
