### ISSUE TITLE
provider not registered

### ISSUE THREAD

**Issue by Gatts011** [dusterio/laravel-aws-worker#86]
Using laravel:^8.12 fresh project, set REGISTER_WORKER_ROUTES=true in .env, after composer require or manually adding to composer.json , provider is never registered in config>app.php>providers array. php artisan route:list route not listed, added routes manually to web.php and post is executed in eb logs but nothing returned to webtier. 

Tried composer dump-autoload and php artisan config:clear

Is there a way to force registration?
Should we use QUEUE_DRIVER=sqs and or QUEUE_CONNECTION=sqs? because using QUEUE_DRIVER alone causes 'default' = 'sync' driver to be used in config>queue.php successfully firing job but with no delay. 
If package was to register, will messages be recieved on local machines?
Do I need cron.yaml if Im only using sqs?

Any help from anyone at this point would be greatly appreciated.

**Comment by kalecio** [comment]
Hey @Gatts011 you will need to add this in your config/app.php as it's stated in the README

```
// Add in your config/app.php

'providers' => [
    '...',
    'Dusterio\AwsWorker\Integrations\LaravelServiceProvider',
];
```
After that you will be able to check those special routes with `php artisan route:list`

You should use QUEUE_CONNECTION=sqs since QUEUE_DRIVER has being substituted by that since laravel 5.7 I think.

You don't need the cron.yaml example if you are not using schedules

**Comment by fylzero** [comment]
@kalecio Thanks for that answer!
